services:
  db:
    image: postgres:16
    container_name: listly_db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      test: [ "CMD-SHELL", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE_DB}" ]
      timeout: 5s
      retries: 5

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listly_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_DB
      - JWT_SECRET_KEY
      - SECRET_KEY
    command: >
      bash -c "flask db upgrade &&
               gunicorn --bind 0.0.0.0:5000 --workers 4 app:app"

volumes:
  postgres_data:
