version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: listly
    restart: unless-stopped
    environment:
      POSTGRES_USER: listly
      POSTGRES_PASSWORD: listly
      POSTGRES_DB: listly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: