services:
  db:
    image: postgres:16
    container_name: listly_db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listly_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "flask db upgrade &&
               gunicorn --bind 0.0.0.0:5000 --workers 4 app:app"

volumes:
  postgres_data: