version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: listly_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: listly
      MYSQL_PASSWORD: listly
      MYSQL_DATABASE: listly
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
