"""add normalized_name to product_suggestion

Revision ID: 041949490566
Revises: 1a463bfff12d
Create Date: 2025-04-03 00:38:49.793170

"""
from alembic import op
import sqlalchemy as sa
import unicodedata


# revision identifiers, used by Alembic.
revision = '041949490566'
down_revision = '1a463bfff12d'
branch_labels = None
depends_on = None


def normalize_text(text):
    """Remove acentos e converte para minúsculas."""
    if not text:
        return ""
    text = text.lower()
    return ''.join(c for c in unicodedata.normalize('NFD', text)
                  if unicodedata.category(c) != 'Mn')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_name', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_product_suggestion_normalized_name'), ['normalized_name'], unique=False)

    # Preenche a coluna normalized_name com os valores normalizados
    conn = op.get_bind()
    
    # Busca todos os produtos
    result = conn.execute(sa.text("SELECT id, name FROM product_suggestion"))
    products = result.fetchall()
    
    # Atualiza cada produto com o nome normalizado
    for product_id, name in products:
        normalized = normalize_text(name)
        conn.execute(
            sa.text("UPDATE product_suggestion SET normalized_name = :normalized WHERE id = :id"),
            {"normalized": normalized, "id": product_id}
        )
    
    # Torna a coluna não nula após preenchê-la
    with op.batch_alter_table('product_suggestion', schema=None) as batch_op:
        batch_op.alter_column('normalized_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_suggestion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_suggestion_normalized_name'))
        batch_op.drop_column('normalized_name')

    # ### end Alembic commands ###
